kind: pipeline
type: docker
name: refresh dependencies

platform:
  os: linux
  arch: arm64

steps:
  - name: update
    image: golang:latest
    commands:
      - go get -u
      - go mod tidy

  - name: push
    image: appleboy/drone-git-push
    settings:
      ssh_key:
        from_secret: ARICODES_PRIVATE_KEY
      branch: main
      remote: git@github.com:aricodes-oss/std.git
      commit: true
      commit_message: 'CHORE: Update dependencies'
